[package]
name = "sdp"
version = "0.1.0"
authors = ["Luo <gnulinux@126.com>"]

[dependencies]
regex = "*"

[dependencies.url]
git = "https://github.com/servo/rust-url"
# features = ["query_encoding"]

